# Generated by Django 3.1.1 on 2020-10-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('question1', models.CharField(max_length=400)),
                ('ans1', models.CharField(choices=[('Sachine Tendulkar', 'Sachine Tendulkar'), ('Virat Kohli', 'Virat Kohli'), ('Adam Gilchirst', 'Adam Gilchirst'), ('Jacques Kallis', 'Jacques Kallis')], max_length=20)),
                ('ans2', models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green')], max_length=20)),
            ],
        ),
    ]
