# Generated by Django 3.1.1 on 2020-10-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ans1',
            field=models.CharField(choices=[('Sachine Tendulkar', 'Sachine Tendulkar'), ('Virat Kohli', 'Virat Kohli'), ('Adam Gilchirst', 'Adam Gilchirst'), ('Jacques Kallis', 'Jacques Kallis')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ans2',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='question1',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
