# Generated by Django 3.1.1 on 2020-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_question',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
