# Generated by Django 3.1.1 on 2020-10-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0007_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='option',
            field=models.CharField(max_length=100),
        ),
    ]
