# Generated by Django 3.1.1 on 2020-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0008_auto_20201020_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'single'), ('multiple', 'multiple')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
