# Generated by Django 3.1.1 on 2020-10-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0009_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trivia_App.person'),
        ),
        migrations.AlterField(
            model_name='result',
            name='option',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trivia_App.question'),
        ),
    ]
