# Generated by Django 3.1.1 on 2020-10-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0010_auto_20201020_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('question', models.CharField(max_length=200, null=True)),
                ('option', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
