# Generated by Django 3.1.1 on 2020-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0011_finalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
