# Generated by Django 3.1.1 on 2020-10-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0012_finalresult_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='question',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
